### ISSUE TITLE
bgfx description is inaccurate nonsense

### ISSUE THREAD

**Issue by bkaradzic** [Gforcex/OpenGraphic#3]
Current bgfx description is inaccurate nonsense:

bgfx - Orthodox C++ coding style and like OpenGL APIs

Please change it to:

bgfx - Cross-platform rendering library

or

bgfx - Cross-platform, graphics API agnostic, "Bring Your Own Engine/Framework" style rendering library.

**Comment by Gforcex** [comment]
bgfx is well known, I wrote the wrong line at that time.  I've changed it. Thanks.

**Comment by bkaradzic** [comment]
Thanks!  :+1:
